package byog.Core;

import byog.SaveDemo.World;
import byog.TileEngine.TETile;
import byog.TileEngine.Tileset;
import edu.princeton.cs.introcs.StdDraw;

import java.util.List;
import java.util.ArrayList;
import java.util.ArrayDeque;
import java.util.Random;

import java.awt.*;

public class MapGenerator {
    private static final int WIDTH = 80;
    private static final int HEIGHT = 30;

    private static final int ROOMMAXLEN = 8;

    private static final int MIN_X = 0;
    private static final int MIN_Y = 0;

    private static final int ROOM_LIMIT = 200;   // maximum number of rooms


    /* Directions */
    private static final int NORTH = 0;
    private static final int SOUTH = 1;
    private static final int WEST = 2;
    private static final int EAST = 3;
    private static final int NORTHWEST = 4;
    private static final int NORTHEAST = 5;
    private static final int SOUTHWEST = 6;
    private static final int SOUTHEAST = 7;


    /* Set font size to displayed. */
    private static final int TITLE_FONT_SIZE = 40;
    private static final int INITIAL_COMMANDS_FONT_SIZE = 30;
    private static final int HUD_FONT_SIZE = 16;


    /**
     * World
     * Generate a random world map contains rooms and hallways.
     */

    private static class World {
        private List<Room> rooms;
        private List<Hallway> hallways;
        private TETile[][] map;

        World() {
            rooms = new ArrayList<>();
            hallways = new ArrayList<>();
            map = new TETile[WIDTH][HEIGHT];
        }
    }

    /**
     * Region
     * The region of rooms and hallways should be connected.
     */
    private static class Region {
        List<Connect> connects;
        boolean connected;
    }

    /**
     * Room
     * The room is completely determined by its coordinates.
     */
    private static class Room extends Region {
        Coordinate topRight;
        Coordinate botLeft;

        Room(Coordinate topRight, Coordinate botLeft) {
            this.topRight = topRight;
            this.botLeft = botLeft;
            connected = false;
            connects = new ArrayList<>();
        }
    }

    /**
     * Hallway
     * Represents a generic hallway.
     */
    private static class Hallway extends Region {
        List<Coordinate> coors;

        Hallway() {
            coors = new ArrayList<>();
            connects = new ArrayList<>();
            connected = false;
        }
    }

    /**
     * Coordinate
     * Coordinates of the world.
     */
    protected static class Coordinate {
        int x;
        int y;

        Coordinate(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }

    /**
     * Connect
     * Connects rooms.
     */
    private static class Connect {
        Coordinate coors;
        Region connectTo;

        Connect(Coordinate coors, Region connectTo) {
            this.coors = coors;
            this.connectTo = connectTo;
        }
    }


    /**
     *
     * @param rand
     * @return
     */
    public static TETile[][] generateWorld(Random rand) {
        World world = new World();
        TETile[][] map = world.map;

        /* Initialize the world. */
        for (int x = 0; x < WIDTH; x++) {
            for (int y = 0; y < HEIGHT; y++) {
                map[x][y] = Tileset.NOTHING;
            }
        }
        // TODO: generate the world with rooms and connect them.
        generateRoom(world, rand);
        generateMaze(world, rand);


        return world.map;
    }

    /**
     * Generates random rooms in the world.
     * @param world the world contains random rooms.
     * @param rand  random generated by seed.
     */
    private static void generateRoom(World world, Random rand) {
        for (int i = 0; i < ROOM_LIMIT; i++) {
            /* Set room size. */
            int botLeftX = RandomUtils.uniform(rand, MIN_X, WIDTH);
            int botLeftY = RandomUtils.uniform(rand, MIN_Y, HEIGHT);
            int topRightX = 2 * RandomUtils.uniform(rand, (botLeftX + 1) / 2,
                    Integer.min(WIDTH, botLeftX + ROOMMAXLEN) / 2);
            int topRightY = 2 * RandomUtils.uniform(rand, (botLeftY + 1) / 2,
                    Integer.min(HEIGHT, botLeftY + ROOMMAXLEN) / 2);

            /* Generate World via Coordinates. */
            Room newRoom = new Room(new Coordinate(botLeftX, botLeftY),
                    new Coordinate(topRightX, topRightY));

            if (!isRoomOverlap(world, newRoom)) {
                world.rooms.add(newRoom);
            }
        }
        fillRoom(world);
    }


    /**
     * Check whether two rooms are overlapped.
     * @param world a list of rooms.
     * @param newRoom  the room to be checked.
     * @return
     */
    private static boolean isRoomOverlap(World world, Room newRoom) {
        for (int i = 0; i < world.rooms.size(); i++) {
            Room curRoom = world.rooms.get(i);
            boolean res;

            res = !(newRoom.topRight.x + 1 < curRoom.botLeft.x
                    || newRoom.topRight.y + 1 < curRoom.botLeft.y
                    || newRoom.botLeft.x - 1 > curRoom.topRight.x
                    || newRoom.botLeft.y - 1 > curRoom.topRight.y);

            if (res) {
                return true;
            }
        }
        return false;
    }

    /**
     * Fill rooms with floors and surround them with walls.
     *
     *  ---------------------------------
     *  |                   tR(x+1, y+1)|
     *  |  W          WALL           W  |
     *  |  A   |-----------------    A  |
     *  |  L   | Room    tR(x,y)|    L  |
     *  |  L   | bL(x,y)        |    L  |
     *  |      -------------------->    |
     *  |bL(x-1, y-1)    WALL           |
     *  ---------------------------------
     * @param world a list of rooms.
     */
    private static void fillRoom(World world) {
        for (int i = 0; i < world.rooms.size(); i++) {
            Room curRoom = world.rooms.get(i);

            /* Floors */
            for (int x = curRoom.botLeft.x; x <= curRoom.topRight.x; x++) {
                for (int y = curRoom.botLeft.y; y <= curRoom.topRight.y; y++) {
                    world.map[x][y] = Tileset.FLOOR;
                }
            }

            /* Walls */
            for (int x = curRoom.botLeft.x - 1; x <= curRoom.topRight.x + 1; x++) {
                world.map[x][curRoom.botLeft.y - 1] = Tileset.WALL;
                world.map[x][curRoom.topRight.y + 1] = Tileset.WALL;
            }

            for (int y = curRoom.botLeft.y ; y <= curRoom.topRight.y; y++) {
                world.map[curRoom.botLeft.x - 1][y] = Tileset.WALL;
                world.map[curRoom.topRight.x + 1][y] = Tileset.WALL;
            }
        }
    }

    /**
     * Maze Generation.
     * @param world a list of rooms.
     * @param rand random generated by seed.
     */
    private static void generateMaze(World world, Random rand) {
        for (int x = 1; x < WIDTH; x++) {
            for (int y = 1; y < HEIGHT; y++) {
                if (world.map[x][y].equals(Tileset.NOTHING)) {
                    Hallway hallway = new Hallway();
                    Coordinate coors = new Coordinate(x, y);
                    fillMaze(world.map, rand, hallway, coors);
                    hallwayWall(world.map, hallway);
                    world.hallways.add(hallway);
                }
            }
        }
    }

    // TODO: fill maze

    /**
     * Generate the maze using the flood fill algorithm.
     * @param worldMap
     * @param rand
     * @param hallway
     * @param coord
     */
    private static void fillMaze(TETile[][] worldMap, Random rand, Hallway hallway, Coordinate coord) {
        int x = coord.x;
        int y = coord.y;
        int lastDir = RandomUtils.uniform(rand, 4);

        /* Check whether it is already filled or if it is at the boundary. */
        if (worldMap[x][y].equals(Tileset.FLOOR) || worldMap[x][y].equals(Tileset.WALL)
                || x == 0 || y == 0 || x == WIDTH || y == HEIGHT) {
            return;
        }

        /* Create a queue and enqueue the coordinates. */
        ArrayDeque<Coordinate> stack = new ArrayDeque<>();
        stack.add(coord);
        hallway.coors.add(coord);
        worldMap[x][y] = Tileset.FLOOR;

        while(!stack.isEmpty()) {
            int dir;
            List<Integer> avblDir = new ArrayList<>();
            coord = stack.getLast();

            for (int i = 0; i < 4; i++) {
                //Coordinate firstCoord = applyDir(i, 1, coord);
                Coordinate secondCoord = applyDir(i, 2, coord);

                /* Unavailable Coordinate.*/
                if (secondCoord.x <= 0 || secondCoord.x >= WIDTH
                        || secondCoord.y <= 0 || secondCoord.y >= HEIGHT) {
                    continue;
                }

                /* Available Coordinate. */
                if (worldMap[secondCoord.x][secondCoord.y].equals(Tileset.NOTHING)) {
                    avblDir.add(i);
                }
            }

            if (!avblDir.isEmpty()) {
                if (avblDir.contains(lastDir) && RandomUtils.uniform(rand, 100) > 40) {
                    dir = lastDir;
                } else {
                    dir = avblDir.get(RandomUtils.uniform(rand, avblDir.size()));
                }

                Coordinate firstCoord = applyDir(dir, 1, coord);
                Coordinate secondCoord = applyDir(dir, 2, coord);
                worldMap[firstCoord.x][firstCoord.y] = Tileset.FLOOR;
                worldMap[secondCoord.x][secondCoord.y] = Tileset.FLOOR;
                stack.addLast(secondCoord);

                if (!hallway.coors.contains(firstCoord)) {
                    hallway.coors.add(firstCoord);
                }
                if (!hallway.coors.contains(secondCoord)) {
                    hallway.coors.add(secondCoord);
                }
                lastDir = dir;
            } else {
                stack.removeLast();
            }
        }
    }

    /**
     * Directions and distance to coordinate.
     * @param dir
     * @param distance
     * @param coord
     * @return  coordinate
     */
    protected static Coordinate applyDir(int dir, int distance, Coordinate coord) {
        switch (dir) {
            case NORTH:
                return new Coordinate(coord.x, coord.y + distance);
            case SOUTH:
                return new Coordinate(coord.x, coord.y - distance);
            case WEST:
                return new Coordinate(coord.x - distance, coord.y);
            case EAST:
                return new Coordinate(coord.x + distance, coord.y);
            case NORTHWEST:
                return new Coordinate(coord.x - 1, coord.y + 1);
            case NORTHEAST:
                return new Coordinate(coord.x + 1, coord.y + 1);
            case SOUTHWEST:
                return new Coordinate(coord.x - 1, coord.y - 1);
            case SOUTHEAST:
                return new Coordinate(coord.x + 1, coord.y - 1);
            default:
                return null;
        }
    }


    /**
     * Generate wall for hallways.
     * @param worldMap
     * @param hallway
     */
    private static void hallwayWall(TETile[][] worldMap, Hallway hallway) {
        for (int i = 0; i < hallway.coors.size(); i++) {
            Coordinate coor = hallway.coors.get(i);
            for (int j = 0; j < 8; j++) {
                Coordinate coor2 = applyDir(j, 1, coor);
                if (worldMap[coor2.x][coor2.y].equals(Tileset.NOTHING)) {
                    worldMap[coor2.x][coor2.y] = Tileset.WALL;
                }
            }
        }
    }


























    protected static Coordinate getPlayer() {
        for (int x = 0; x < WIDTH; x++) {
            for (int y = 0; y < WIDTH; y++) {
                // TODO: find the player and return it

            }
        }

        return null;

    }











    protected static void displayMessage(String message) {
        Font font = StdDraw.getFont();
        StdDraw.clear(StdDraw.BLACK);
        StdDraw.setPenColor(Color.WHITE);
        StdDraw.setFont(font.deriveFont(Font.BOLD, TITLE_FONT_SIZE));
        StdDraw.text(WIDTH / 2, HEIGHT / 2, message);
        StdDraw.setFont(font);
        StdDraw.show();
    }





}
