package byog.Core;

import byog.TileEngine.TETile;
import byog.TileEngine.Tileset;
import java.util.List;
import java.util.ArrayList;
import java.util.ArrayDeque;
import java.util.Random;


/**
 * MapGenerator
 * A class to generate a random world consisting of rooms, hallways, and walls.
 * @author Terry
 */
public class MapGenerator {
    /* Properties of the world. */
    public static final int WIDTH = 81;
    public static final int HEIGHT = 31;
    private static final int ROOMMAXLEN = 9;
    private static final int ROOM_LIMIT = 200;
    private static final int MIN_X = 0;
    private static final int MIN_Y = 0;

    /* Directions. */
    public static final int NORTH = 0;
    public static final int SOUTH = 1;
    public static final int WEST = 2;
    public static final int EAST = 3;
    public static final int NORTHWEST = 4;
    public static final int NORTHEAST = 5;
    public static final int SOUTHWEST = 6;
    public static final int SOUTHEAST = 7;

    /**
     * World
     * Generate a random world map contains rooms and hallways.
     */
    private static class World {
        private List<Room> rooms;
        private List<Hallway> hallways;
        private TETile[][] map;

        World() {
            rooms = new ArrayList<>();
            hallways = new ArrayList<>();
            map = new TETile[WIDTH][HEIGHT];
        }
    }

    /**
     * Region
     * The region of rooms and hallways should be connected.
     */
    private static class Region {
        List<Connect> connects;
        boolean connected;
    }

    /**
     * Room
     * The room is completely determined by its coordinates.
     */
    private static class Room extends Region {
        Coordinate topRight;
        Coordinate botLeft;

        Room(Coordinate botLeft, Coordinate topRight) {
            this.botLeft = botLeft;
            this.topRight = topRight;
            connected = false;
            connects = new ArrayList<>();
        }
    }

    /**
     * Hallway
     * Represents a generic hallway.
     */
    private static class Hallway extends Region {
        List<Coordinate> coors;

        Hallway() {
            coors = new ArrayList<>();
            connects = new ArrayList<>();
            connected = false;
        }
    }

    /**
     * Coordinate
     * Coordinates of the world.
     */
    protected static class Coordinate {
        int x;
        int y;

        Coordinate(int x, int y) {
            this.x = x;
            this.y = y;
        }
    }

    /**
     * Connect
     * Connects rooms.
     */
    private static class Connect {
        Coordinate coors;
        Region connectTo;

        Connect(Coordinate coors, Region connectTo) {
            this.coors = coors;
            this.connectTo = connectTo;
        }
    }

    /**
     * Randomly world generate.
     * @param rand
     * @return  a random world.
     */
    public static TETile[][] generateWorld(Random rand) {
        World world = new World();
        TETile[][] map = world.map;
        /* Initialize the world. */
        for (int x = 0; x < WIDTH; x++) {
            for (int y = 0; y < HEIGHT; y++) {
                map[x][y] = Tileset.NOTHING;
            }
        }
        /* Generate the world. */
        generateRoom(world, rand);
        generateMaze(world, rand);
        findConnects(world);
        connectRegions(world, rand);
        removeDeadEnds(world);      // Comment this line to generate a square world without dead ends.
        addDoorAndCharacter(world, rand);
        return world.map;
    }

    /**
     * Generates random rooms in the world.
     * @param world the world contains random rooms.
     * @param rand  random generated by seed.
     */
    private static void generateRoom(World world, Random rand) {
        for (int i = 0; i < ROOM_LIMIT; i++) {
            /* Set room size. */
            int botLeftX = 2 * RandomUtils.uniform(rand, MIN_X,  (WIDTH - 3) / 2) + 1;
            int botLeftY = 2 * RandomUtils.uniform(rand, MIN_Y, (HEIGHT - 3) / 2) + 1;
            int topRightX = 2 * RandomUtils.uniform(rand, (botLeftX + 1) / 2,
                    Integer.min(WIDTH - 1, botLeftX + ROOMMAXLEN) / 2) + 1;
            int topRightY = 2 * RandomUtils.uniform(rand, (botLeftY + 1) / 2,
                    Integer.min(HEIGHT - 1, botLeftY + ROOMMAXLEN) / 2) + 1;
            /* Generate rooms using Coordinates. */
            Room newRoom = new Room(new Coordinate(botLeftX, botLeftY),
                    new Coordinate(topRightX, topRightY));
            /* Rooms should not overlap. */
            if (!isRoomOverlap(world, newRoom)) {
                world.rooms.add(newRoom);
            }
        }
        fillRoom(world);
    }

    /**
     * Check whether two rooms are overlapped.
     * @param world a list of rooms.
     * @param newRoom  the room to be checked.
     * @return
     */
    private static boolean isRoomOverlap(World world, Room newRoom) {
        for (int i = 0; i < world.rooms.size(); i++) {
            Room curRoom = world.rooms.get(i);
            boolean res;

            /* Verify if two rooms share the same boundary. */
            res = !(newRoom.topRight.x + 1 < curRoom.botLeft.x
                    || newRoom.topRight.y + 1 < curRoom.botLeft.y
                    || newRoom.botLeft.x - 1 > curRoom.topRight.x
                    || newRoom.botLeft.y - 1 > curRoom.topRight.y);

            if (res) {
                return true;
            }
        }
        return false;
    }

    /**
     * Fill rooms with floors and surround them with walls.
     *  ---------------------------------
     *  |                   tR(x+1, y+1)|
     *  |  W          WALL           W  |
     *  |  A   |-----------------    A  |
     *  |  L   | Room    tR(x,y)|    L  |
     *  |  L   | bL(x,y)        |    L  |
     *  |      -------------------->    |
     *  |bL(x-1, y-1)    WALL           |
     *  ---------------------------------
     * @param world a list of rooms.
     */
    private static void fillRoom(World world) {
        for (int i = 0; i < world.rooms.size(); i++) {
            Room curRoom = world.rooms.get(i);

            /* Floor tiles within the room. */
            for (int x = curRoom.botLeft.x; x <= curRoom.topRight.x; x++) {
                for (int y = curRoom.botLeft.y; y <= curRoom.topRight.y; y++) {
                    world.map[x][y] = Tileset.FLOOR;
                }
            }

            /* Walls encircle the room. */
            for (int x = curRoom.botLeft.x - 1; x <= curRoom.topRight.x + 1; x++) {
                world.map[x][curRoom.botLeft.y - 1] = Tileset.WALL;
                world.map[x][curRoom.topRight.y + 1] = Tileset.WALL;
            }
            for (int y = curRoom.botLeft.y ; y <= curRoom.topRight.y; y++) {
                world.map[curRoom.botLeft.x - 1][y] = Tileset.WALL;
                world.map[curRoom.topRight.x + 1][y] = Tileset.WALL;
            }
        }
    }

    /**
     * Maze Generation.
     * @param world a list of rooms.
     * @param rand random generated by seed.
     */
    private static void generateMaze(World world, Random rand) {
        for (int x = 1; x < WIDTH - 1; x++) {
            for (int y = 1; y < HEIGHT - 1; y++) {
                if (world.map[x][y].equals(Tileset.NOTHING)) {
                    Hallway hallway = new Hallway();
                    Coordinate coors = new Coordinate(x, y);
                    fillMaze(world.map, rand, hallway, coors);
                    hallwayWall(world.map, hallway);
                    world.hallways.add(hallway);
                }
            }
        }
    }

    /**
     * Generate the maze using the flood fill algorithm.
     * @param worldMap
     * @param rand
     * @param hallway
     * @param coord
     */
    private static void fillMaze(TETile[][] worldMap, Random rand, Hallway hallway, Coordinate coord) {
        int x = coord.x;
        int y = coord.y;
        int lastDir = RandomUtils.uniform(rand, 4);

        /* Check if it is already filled or if it is at the boundary. */
        if (worldMap[x][y].equals(Tileset.FLOOR) || worldMap[x][y].equals(Tileset.WALL)
                || x == 0 || y == 0 || x == WIDTH - 1 || y == HEIGHT - 1) {
            return;
        }

        /* Create a queue and enqueue the coordinates. */
        ArrayDeque<Coordinate> stack = new ArrayDeque<>();
        stack.add(coord);
        hallway.coors.add(coord);
        worldMap[x][y] = Tileset.FLOOR;

        /* Flood Fill Algorithm. */
        while(!stack.isEmpty()) {
            int dir;
            List<Integer> avblDir = new ArrayList<>();
            coord = stack.getLast();

            for (int i = 0; i < 4; i++) {
                Coordinate two_steps = applyDir(i, 2, coord);

                /* Unavailable Coordinate.*/
                if (two_steps.x <= 0 || two_steps.x >= WIDTH -1
                        || two_steps.y <= 0 || two_steps.y >= HEIGHT -1) {
                    continue;
                }

                /* Available Coordinate. */
                if (worldMap[two_steps.x][two_steps.y].equals(Tileset.NOTHING)) {
                    avblDir.add(i);
                }
            }

            if (!avblDir.isEmpty()) {
                if (avblDir.contains(lastDir) && RandomUtils.uniform(rand, 100) > 40) {
                    dir = lastDir;
                } else {
                    dir = avblDir.get(RandomUtils.uniform(rand, avblDir.size()));
                }

                Coordinate one_step = applyDir(dir, 1, coord);
                Coordinate two_steps = applyDir(dir, 2, coord);
                worldMap[one_step.x][one_step.y] = Tileset.FLOOR;
                worldMap[two_steps.x][two_steps.y] = Tileset.FLOOR;
                stack.addLast(two_steps);

                if (!hallway.coors.contains(one_step)) {
                    hallway.coors.add(one_step);
                }
                if (!hallway.coors.contains(two_steps)) {
                    hallway.coors.add(two_steps);
                }
                lastDir = dir;
            } else {
                stack.removeLast();
            }
        }
    }

    /**
     * Directions and distance to coordinate.
     * @param dir       directions
     * @param distance  distance to move
     * @param coord     the coordinate
     * @return          coordinate after moving.
     */
    protected static Coordinate applyDir(int dir, int distance, Coordinate coord) {
        switch (dir) {
            case NORTH:
                return new Coordinate(coord.x, coord.y + distance);
            case SOUTH:
                return new Coordinate(coord.x, coord.y - distance);
            case WEST:
                return new Coordinate(coord.x - distance, coord.y);
            case EAST:
                return new Coordinate(coord.x + distance, coord.y);
            case NORTHWEST:
                return new Coordinate(coord.x - 1, coord.y + 1);
            case NORTHEAST:
                return new Coordinate(coord.x + 1, coord.y + 1);
            case SOUTHWEST:
                return new Coordinate(coord.x - 1, coord.y - 1);
            case SOUTHEAST:
                return new Coordinate(coord.x + 1, coord.y - 1);
            default:
                return null;
        }
    }

    /**
     * Generate wall for hallways.
     * @param worldMap
     * @param hallway
     */
    private static void hallwayWall(TETile[][] worldMap, Hallway hallway) {
        for (int i = 0; i < hallway.coors.size(); i++) {
            Coordinate coord = hallway.coors.get(i);
            for (int j = 0; j < 8; j++) {
                /* Neighbors in all eight directions of the current hallway coordinates. */
                Coordinate coord2 = applyDir(j, 1, coord);
                if (worldMap[coord2.x][coord2.y].equals(Tileset.NOTHING)) {
                    worldMap[coord2.x][coord2.y] = Tileset.WALL;
                }
            }
        }
    }

    /**
     * Two spaces should be separated by a wall. A coordinate inside the wall should contain
     * a maximum of 2 floor coordinates (either above and below or left and right).
     * This implies that if two coordinates are present, the spaces are adjacent and should connect.
     * @param world
     */
    private static void findConnects(World world) {
        for (int x = 1; x < WIDTH - 1; x++) {
            for (int y = 1; y < HEIGHT -1 ; y++) {
                if (world.map[x][y].equals(Tileset.WALL)) {
                    List<Coordinate> floor_coord = new ArrayList<>();
                    /* Check if the coordinate adjacent to the wall is a floor. */
                    for (int i = 0; i < 4; i++) {
                        Coordinate exp_coord = applyDir(i, 1, new Coordinate(x, y));
                        if (world.map[exp_coord.x][exp_coord.y].equals(Tileset.FLOOR)) {
                            floor_coord.add(exp_coord);
                        }
                    }
                    /* If the spaces are adjacent. */
                    if (floor_coord.size() == 2) {
                        /* Determine which room or hallway the two floors belong to. */
                        List<Region> belongsTo = new ArrayList<>();
                        for (int i = 0; i < 2; i++) {
                            Coordinate temp = floor_coord.get(i);
                            for (int j = 0; j < world.rooms.size(); j++) {
                                Room temp_room = world.rooms.get(j);
                                if (((temp.x == temp_room.botLeft.x || temp.x == temp_room.topRight.x)
                                        && (temp.y >= temp_room.botLeft.y && temp.y <= temp_room.topRight.y))
                                        || ((temp.y == temp_room.botLeft.y || temp.y == temp_room.topRight.y)
                                        && (temp.x >= temp_room.botLeft.x && temp.x <= temp_room.topRight.x))) {
                                    belongsTo.add(temp_room);
                                    break;
                                }
                            }
                            for (int j = 0; j < world.hallways.size(); j++) {
                                Hallway temp_hallway = world.hallways.get(j);
                                for (int m = 0; m < temp_hallway.coors.size(); m++) {
                                    Coordinate temp_coord = temp_hallway.coors.get(m);
                                    if (temp_coord.x == temp.x && temp_coord.y == temp.y) {
                                        belongsTo.add(temp_hallway);
                                    }
                                }
                            }
                        }
                        if (belongsTo.size() == 2 && !belongsTo.get(0).equals(belongsTo.get(1))) {
                            for (int i = 0; i < 2; i++) {
                                Region region = belongsTo.get(i);
                                region.connects.add(new Connect(new Coordinate(x, y),
                                        belongsTo.get(1 - i)));
                            }
                        }
                    }
                }
            }
        }
    }

    /**
     * Connect rooms and hallways.
     * @param world
     * @param rand
     */
    private static void connectRegions(World world, Random rand) {
        int index_rooms = RandomUtils.uniform(rand, world.rooms.size());
        List<Connect> list_connects = new ArrayList<>(world.rooms.get(index_rooms).connects);
        world.rooms.get(index_rooms).connected = true;

        while (!list_connects.isEmpty()) {
            int index_connects = RandomUtils.uniform(rand, list_connects.size());
            Connect cont = list_connects.get(index_connects);
            Coordinate coord = cont.coors;
            if (!cont.connectTo.connected) {
                world.map[coord.x][coord.y] = Tileset.FLOOR;
            }

            /* There's a slight chance of having multiple connections to a single region,
               and these should be removed from the connects. */
            for (int i = 0; i < list_connects.size(); i++) {
                Connect cnt = list_connects.get(i);
                Coordinate coor = cnt.coors;
                Region the_region = cnt.connectTo;
                if (the_region.connected) {
                    if (RandomUtils.uniform(rand, 100) < 1) {
                        world.map[coor.x][coor.y] = Tileset.FLOOR;
                    }
                    list_connects.remove(i);
                }
            }

            Region region_connected = cont.connectTo;
            if (!region_connected.connected) {
                for (int i = 0; i < region_connected.connects.size(); i++) {
                    list_connects.add(region_connected.connects.get(i));
                }
                region_connected.connected = true;
            }
        }
    }

    /**
     * Remove all the dead ends on the map.
     * @param world
     */
    private static void removeDeadEnds(World world) {
        while (true) {
            boolean no_DeadEnds = true;
            for (int x = 0; x < WIDTH; x++) {
                for (int y = 0; y < HEIGHT; y++) {
                    if (world.map[x][y].equals(Tileset.FLOOR)) {
                        int count = 0;
                        for (int i = 0; i < 4; i++) {
                            Coordinate coord = applyDir(i, 1, new Coordinate(x, y));
                            if (world.map[coord.x][coord.y].equals(Tileset.WALL)) {
                                count++;
                            }
                        }
                        /* A dead end should have three directions blocked by walls. */
                        if (count == 3) {
                            world.map[x][y] = Tileset.WALL;
                            no_DeadEnds = false;
                        }
                    }
                }
            }
            if (no_DeadEnds) {
                break;
            }
        }

        /* Remove extra walls. */
        List<Coordinate> to_remove = new ArrayList<>();
        for (int x = 0; x < WIDTH; x++) {
            for (int y = 0; y < HEIGHT; y++) {
                boolean redundant = true;
                for (int i = 0; i < 8; i++) {
                    Coordinate coord = applyDir(i, 1, new Coordinate(x, y));
                    if (coord.x < 0 || coord.x >= WIDTH || coord.y < 0 || coord.y >= HEIGHT) {
                        continue;
                    }
                    if (!world.map[coord.x][coord.y].equals(Tileset.WALL)) {
                        redundant = false;
                        break;
                    }
                }
                if (redundant) {
                    to_remove.add(new Coordinate(x, y));
                }
            }
        }
        for (int i = 0; i < to_remove.size(); i++) {
            Coordinate coord = to_remove.get(i);
            world.map[coord.x][coord.y] = Tileset.NOTHING;
        }
    }

    /**
     * Randomly add a door to the floor and a potions of a player.
     * @param world
     * @param rand
     */
    private static void addDoorAndCharacter(World world, Random rand) {
        List<Coordinate> door = new ArrayList<>();
        List<Coordinate> player = new ArrayList<>();
        /* Scan all walls and floors for door and player coordinates. */
        for (int x = 0; x < WIDTH; x++) {
            for (int y = 0; y < HEIGHT; y++) {
                if (world.map[x][y].equals(Tileset.WALL)) {
                    boolean has_nothing = false;
                    boolean has_floor = false;
                    /* The coordinates of the door and its two neighbors should be within the wall.
                       The other two neighbors should be either off the map or on floors.*/
                    for (int i = 0; i < 4; i++) {
                        Coordinate coord = applyDir(i, 1, new Coordinate(x, y));
                        if (coord.x < 0 || coord.x >= WIDTH || coord.y < 0 || coord.y >= HEIGHT) {
                            has_nothing = true;
                            continue;
                        }
                        if (world.map[coord.x][coord.y].equals(Tileset.FLOOR)) {
                            has_floor = true;
                        } else if (world.map[coord.x][coord.y].equals(Tileset.NOTHING)) {
                            has_nothing = true;
                        }
                    }
                    if (has_floor && has_nothing) {
                        door.add(new Coordinate(x, y));
                    }
                } else if (world.map[x][y].equals(Tileset.FLOOR)) {
                    player.add(new Coordinate(x, y));
                }
            }
        }
        /* Position of a random door. */
        int index = RandomUtils.uniform(rand, door.size());
        Coordinate coord = door.get(index);
        world.map[coord.x][coord.y] = Tileset.LOCKED_DOOR;

        /* Position of a random player. */
        index = RandomUtils.uniform(rand, player.size());
        coord = player.get(index);
        world.map[coord.x][coord.y] = Tileset.PLAYER;
    }
}
